### ISSUE TITLE
Model size conflit

### ISSUE THREAD

**Issue by ZheyuYe** [google-research/electra#39]
There seems to be a confilt about generator sizes. That of electra small/base/large are 1/4, 1/3, 1/4 as lastest paper claimed. However, the provided pre-trained weights conflit that with generator size 1, 1/3, 1/4 respectively.

**Comment by clarkkev** [comment]
Yes, as we note in the README the generator size is 1 for the ELECTRA-Small model. We will update the paper with this information too.

**Comment by heartcored98** [comment]
Hi, I really like ELECTRA model. but I am also wondering the reason you chosen to upload the generator model with the hidden size of 256 in case of small model as the official model. Because Figure 3 in your paper shows that generator hidden size with 64 was the best model when the discriminator hidden size was 256.

Is generator of hidden size 256 best for the small model?

**Comment by lucadiliello** [comment]
Which `generator_size` did you use in the paper when reporting results on `electra small`?
