### ISSUE TITLE
Should dynamic masking also ignore ['PAD']

### ISSUE THREAD

**Issue by ccchang0111** [google-research/electra#59]
Here is a set of tokens that should not be masked during dynamic masking.
https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/pretrain/pretrain_helpers.py#L121

But should we also avoid masking all those `['PAD']` at the end of a sentence (if the sentence is shorter than `max_seq_length` and if there is no second sentence segment)?  

I understand `['PAD']` itself has token_id = 0, but I do not see this being used to prevent masking in downstream steps. If we do not ignore it, this will affect the probability calculation here
https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/pretrain/pretrain_helpers.py#L167-L170

Also, we will be trying to predict 'PAD' that is outside a sequence, which is a bit unintuitive. 

Maybe I am missing something here. Thanks again for putting up such a great work!

**Comment by ccchang0111** [comment]
ah never mind, because ['PAD'] is always 0, which automatically makes itself not masked within this function.

**Comment by clarkkev** [comment]
Good question! We don't need to add PAD to the ignore ids because of this line: https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/pretrain/pretrain_helpers.py#L125
the `input_mask` is 1 for non-padding tokens and 0 for padding. But I do agree it would have been clearer in the code if I just had added PAD to the `ignore_ids` instead.

**Comment by ccchang0111** [comment]
ah that's true.. it was already taken care of during data generation process. Thanks for the response! I actually have a PR here that adds [PAD] into the ignore. But feel free to merge or drop it https://github.com/google-research/electra/pull/60
